import streamlit as st
import numpy as np
import pandas as pd
import hashlib
import time
import os
from datetime import datetime

# --- CONFIGURATION ---
st.set_page_config(page_title="EcoLens AI | Phase 2 Dashboard", layout="wide")

# Custom CSS (Keeping your original Phase 1 branding)
st.markdown(f"""
    <style>
    [data-testid="column"]:nth-child(1) {{
        background-color: #23273b;
        padding: 25px;
        border-radius: 15px;
        color: white;
    }}
    .huge-text {{
        font-size: 45px !important;
        font-weight: 800 !important;
        line-height: 1.2;
        margin-bottom: 5px;
    }}
    .huge-label {{
        font-size: 18px;
        text-transform: uppercase;
        color: #555;
        letter-spacing: 1px;
    }}
    .audit-box, .impact-box {{
        background: linear-gradient(145deg, #1e2233, #161928);
        border: 1px solid rgba(255, 255, 255, 0.1);
        border-radius: 12px;
        padding: 24px;
        height: 195px; 
        color: white;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        box-shadow: 0 4px 15px rgba(0,0,0,0.3);
    }}
    .hash-text {{
        font-family: 'Courier New', monospace;
        word-break: break-all;
        font-size: 0.8rem;
        line-height: 1.4;
        color: #4cc9f0;
        background: rgba(0,0,0,0.3);
        padding: 10px;
        border-radius: 8px;
    }}
    .status-pill {{
        display: inline-block;
        padding: 4px 12px;
        background: rgba(0, 255, 127, 0.1);
        border: 1px solid #00ff7f;
        color: #00ff7f;
        border-radius: 20px;
        font-size: 0.75rem;
        font-weight: bold;
    }}
    .margin-widget {{
        background-color: rgba(255, 255, 255, 0.05);
        padding: 15px;
        border-radius: 10px;
        margin-bottom: 15px;
        border: 1px solid rgba(255, 255, 255, 0.1);
    }}
    </style>
""", unsafe_allow_html=True)

# --- PHASE 2 PERSISTENCE LOGIC ---
# This looks for the audit file generated by your IP Camera/Pi script
AUDIT_FILE = "ecolens_audit_log.csv"

def load_audit_data():
    if os.path.exists(AUDIT_FILE):
        return pd.read_csv(AUDIT_FILE)
    return pd.DataFrame(columns=["Timestamp", "Item", "CO2_Saved", "Value_AED", "Block_Hash"])

# --- DATA MAPPING ---
WASTE_METADATA = {
    "PET Plastic Bottles": {"points": 5, "bin": "🔴 Red / 🟡 Yellow"},
    "Aluminum Cans": {"points": 7, "bin": "⚪ Grey / 🔘 Silver"},
    "Paper Waste": {"points": 5, "bin": "🔵 Blue"},
    "General Waste": {"points": 1, "bin": "⚫ Black"},
    "Organic Waste": {"points": 5, "bin": "🟤 Brown"},
    "Specialty Handling": {"points": 15, "bin": "🔘 Clear / 🟠 Orange"}
}

# --- LAYOUT ---
margin, main_content = st.columns([1, 2.8], gap="large")

# --- LEFT MARGIN ---
with margin:
    st.markdown("### 🛰️ System Status")
    st.success("Network: Connected")
    st.info("Node: DXB-UAE-MAIN-B2")
    
    st.divider()
    st.markdown("### ⚖️ Regulatory Alignment")
    st.markdown(f"""<div class="margin-widget">
        <b>Climate Change Law</b><br>
        <i>Federal Decree-Law No. 11 (2024)</i><br>
        Mandates GHG reporting & reductions.
    </div>""", unsafe_allow_html=True)

    if st.button("Clear Audit Cache"):
        if os.path.exists(AUDIT_FILE):
            os.remove(AUDIT_FILE)
        st.rerun()

# --- MAIN CONTENT AREA ---
with main_content:
    st.title("♻️ EcoLens AI | Waste Intelligence Monitor")
    st.markdown("#### Real-Time Compliance Audit Flow")
    
    # Load current data from file
    df_hist = load_audit_data()
    
    # Metrics Calculation
    t_co2 = df_hist['CO2_Saved'].sum() if not df_hist.empty else 0
    t_val = df_hist['Value_AED'].sum() if not df_hist.empty else 0
    t_points = len(df_hist) * 5 # Simplified for demo or map to metadata

    # --- KPI DISPLAY ---
    c1, c2, c3 = st.columns(3)
    c1.markdown(f'<p class="huge-label">CO₂ Prevented</p><p class="huge-text">{t_co2:.3f}kg</p>', unsafe_allow_html=True)
    c2.markdown(f'<p class="huge-label">Est. Market Value</p><p class="huge-text">{t_val:.2f} AED</p>', unsafe_allow_html=True)
    c3.markdown(f'<p class="huge-label">Verified Events</p><p class="huge-text">{len(df_hist)}</p>', unsafe_allow_html=True)

    st.divider()

    # --- INVENTORY TABLE (Aggregated from Audit File) ---
    st.subheader("🗃️ Waste Segregation Inventory")
    inventory_summary = []
    for material, meta in WASTE_METADATA.items():
        count = len(df_hist[df_hist['Item'] == material]) if not df_hist.empty else 0
        inventory_summary.append({
            "Material Type": material,
            "Total Scanned": count,
            "Target Bin": meta['bin'],
            "Status": "Optimized" if count > 0 else "Idle"
        })
    st.table(pd.DataFrame(inventory_summary))

    # --- FOOTER WIDGETS ---
    if not df_hist.empty:
        last_hash = df_hist.iloc[-1]['Block_Hash']
        phones_charged = t_co2 * 121.6
        
        w_col1, w_col2 = st.columns(2)
        with w_col1:
            st.markdown(f"""
                <div class="audit-box">
                    <div class="box-title">🛡️ Verified Audit Log</div>
                    <div class="hash-text"><b>Latest Block:</b><br>{last_hash}</div>
                    <div style="display: flex; justify-content: space-between; align-items: center;">
                        <span style="font-size:0.8rem; color:#aab0c4;">Integrity: 100%</span>
                        <span class="status-pill">VERIFIED</span>
                    </div>
                </div>
            """, unsafe_allow_html=True)
            
        with w_col2:
            st.markdown(f"""
                <div class="impact-box">
                    <div class="box-title">🌍 UAE Net Zero Impact</div>
                    <div>
                        <div style="font-size: 0.9rem;">Equivalent Smartphone Charges</div>
                        <div class="impact-value">🔋 {int(phones_charged)}</div>
                    </div>
                    <div style="font-size: 0.7rem; opacity: 0.7;">Based on EPA GHG Equivalencies</div>
                </div>
            """, unsafe_allow_html=True)

        st.write("")
        csv_data = df_hist.to_csv(index=False).encode('utf-8')
        st.download_button(
            label="📩 Download Audit Ready Report (CSV)",
            data=csv_data,
            file_name=f"Phase2_Waste_Audit.csv",
            mime="text/csv",
            use_container_width=True
        )
    else:
        st.info("Awaiting data from Edge Device (Raspberry Pi Node)...")
        # Auto-refresh to check for new data every 5 seconds
        time.sleep(5)
        st.rerun()